import Container from "@/components/util/Container";
import Link from "next/link";

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen">
      <Container>
        {/* PRIVACY POLICY GENERATED BY LAWDEPOT */}
        <div className=" px-6 py-4 bg-base-100 opacity-80 backdrop-blur-md w-full mx-auto max-w-3xl">
          <h2 className="text-center font-bold underline mb-1">
            watchparty-six.vercel.app Privacy Policy
          </h2>
          <p className="text-center font-thin">
            Type of website: Social Network and Event Creator
            <br />
            Effective date: 5th day of November, 2023
          </p>

          {/* Info */}
          <div className="mt-4">
            <p>
              watchparty-six.vercel.app (the "Site") is owned and operated by
              WatchParty. WatchParty can be contacted at: <br />
              <br />
              tjklimoski@gmail.com
              <br />
              (305) 877-6434
              <br />
              172 Evergreen Rd., Hiawassee, GA, 30546
            </p>
          </div>

          {/* Purpose */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Purpose</h3>
            <p>
              The purpose of this privacy policy (this "Privacy Policy") is to
              inform users of our Site of the following:
            </p>
            <ol className="list-decimal [&>*]:mb-5 pl-8">
              <li>The personal data we will collect;</li>
              <li>Use of collected data;</li>
              <li>Who has access to the data collected;</li>
              <li>The rights of Site users; and</li>
              <li>The Site's cookie policy.</li>
            </ol>
            <p>
              This Privacy Policy applies in addition to the{" "}
              <Link
                href="/terms-of-service"
                className="underline text-primary hover:text-primary-focus focus:text-primary-focus"
              >
                terms and conditions
              </Link>{" "}
              of our Site.
            </p>
          </div>

          {/* Consent */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Consent</h3>
            <p>By using our Site users agree that they consent to:</p>
            <ol className="list-decimal [&>*]:mb-5 pl-8">
              <li>The conditions set out in this Privacy Policy; and</li>
              <li>
                The collection, use, and retention of the data listed in this
                Privacy Policy.
              </li>
            </ol>
          </div>

          {/* Personal Data We Collect */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">
              Personal Data We Collect
            </h3>
            <p>
              We only collect data that helps us achieve the purpose set out in
              this Privacy Policy. We will not collect any additional data
              beyond the data listed below without notifying you first.
            </p>
          </div>

          {/* Data Collected Automatically */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">
              Personal Data We Collect
            </h3>
            <p>
              When you visit and use our Site, we may automatically collect and
              store the following information:
            </p>
            <ol className="list-decimal [&>*]:mb-5 pl-8">
              <li>Location.</li>
            </ol>
          </div>

          {/* Data Collected in a Non-Automatic Way */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">
              Data Collected in a Non-Automatic Way
            </h3>
            <p>
              We may also collect the following data when you perform certain
              functions on our Site:
            </p>
            <ol className="list-decimal [&>*]:mb-5 pl-8">
              <li>First and last name;</li>
              <li>Email address;</li>
              <li>Profile image;</li>
              <li>Address / Location; and</li>
              <li>Auto fill data.</li>
            </ol>
            <p>This data may be collected using the following methods:</p>
            <ol className="list-decimal [&>*]:mb-5 pl-8">
              <li>When the user creates an account;</li>
              <li>When the user updates their information; and</li>
              <li>When the user creates a WatchParty event.</li>
            </ol>
          </div>

          {/* How We Use Personal Data */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">
              How We Use Personal Data
            </h3>
            <p>
              Data collected on our Site will only be used for the purposes
              specified in this Privacy Policy or indicated on the relevant
              pages of our Site. We will not use your data beyond what we
              disclose in this Privacy Policy.
              <br />
              <br />
              The data we collect automatically is used for the following
              purposes:
            </p>
            <ol className="list-decimal [&>*]:mb-5 pl-8">
              <li>
                To serve the user WatchParty events that are near to them based
                on their location.
              </li>
            </ol>
            <p>
              The data we collect when the user performs certain functions may
              be used for the following purposes:
            </p>
            <ol className="list-decimal [&>*]:mb-5 pl-8">
              <li>Communication;</li>
              <li>Populate WatchParty Event pages; and</li>
              <li>Populate User public profile page.</li>
            </ol>
          </div>

          {/* Who We Share Personal Data With */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">
              Who We Share Personal Data With
            </h3>
            <p>
              <span className="underline">Employees</span>
              <br />
              We may disclose user data to any member of our organization who
              reasonably needs access to user data to achieve the purposes set
              out in this Privacy Policy.
            </p>
          </div>

          {/* Other Disclosures */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Other Disclosures</h3>
            <p>
              We will not sell or share your data with other third parties,
              except in the following cases:
            </p>
            <ol className="list-decimal [&>*]:mb-5 pl-8">
              <li>If the law requires it;</li>
              <li>If it is required for any legal proceeding;</li>
              <li>To prove or protect our legal rights; and</li>
              <li>
                To buyers or potential buyers of this company in the event that
                we seek to sell the company.
              </li>
            </ol>
            <p>
              If you follow hyperlinks from our Site to another Site, please
              note that we are not responsible for and have no control over
              their privacy policies and practices.
            </p>
          </div>

          {/* How Long We Store Personal Data */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">
              How Long We Store Personal Data
            </h3>
            <p>
              User data will be stored for 14 days.
              <br />
              <br />
              You will be notified if your data is kept for longer than this
              period.
            </p>
          </div>

          {/* How We Protect Your Personal Data */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">
              How We Protect Your Personal Data
            </h3>
            <p>
              All data is stored on databases in secure facilities. Passwords
              are salted and hashed. All data is only accessible to our
              employees. User accounts are automatically deleted, along with any
              associated data, after 14 days.
              <br />
              <br />
              While we take all reasonable precautions to ensure that user data
              is secure and that users are protected, there always remains the
              risk of harm. The Internet as a whole can be insecure at times and
              therefore we are unable to guarantee the security of user data
              beyond what is reasonably practical.
            </p>
          </div>

          {/* Children */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Children</h3>
            <p>
              We do not knowingly collect or use personal data from children
              under 13 years of age. If we learn that we have collected personal
              data from a child under 13 years of age, the personal data will be
              deleted as soon as possible. If a child under 13 years of age has
              provided us with personal data their parent or guardian may
              contact our privacy officer.
            </p>
          </div>

          {/* How to Access, Modify, Delete, or Challenge the Data Collected */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">
              How to Access, Modify, Delete, or Challenge the Data Collected
            </h3>
            <p>
              If you would like to know if we have collected your personal data,
              how we have used your personal data, if we have disclosed your
              personal data and to who we disclosed your personal data, or if
              you would like your data to be deleted or modified in any way,
              please contact our privacy officer here:
              <br />
              <br />
              Torrance Klimoski
              <br />
              tjklimoski@gmail.com
              <br />
              (305) 877-6434
              <br />
              172 Evergreen Rd., Hiawassee, GA, 30546
            </p>
          </div>

          {/* Do Not Track Notice */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Do Not Track Notice</h3>
            <p>
              Do Not Track ("DNT") is a privacy preference that you can set in
              certain web browsers. We do not track the users of our Site over
              time and across third party websites and therefore do not respond
              to browser-initiated DNT signals.
            </p>
          </div>

          {/* Cookie Policy */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Cookie Policy</h3>
            <p>
              A cookie is a small file, stored on a user's hard drive by a
              website. Its purpose is to collect data relating to the user's
              browsing habits. You can choose to be notified each time a cookie
              is transmitted. You can also choose to disable cookies entirely in
              your internet browser, but this may decrease the quality of your
              user experience.
            </p>
            <br />
            <p>We use the following types of cookies on our Site:</p>
            <ol className="list-decimal [&>*]:mb-5 pl-8">
              <li>
                <span className="underline">Functional cookies</span>
                <br />
                Functional cookies are used to remember the selections you make
                on our Site so that your selections are saved for your next
                visits.
                <br />
              </li>
              <li>
                <span className="underline">User authentication cookies</span>
                <br />
                User authentication cookies are used to persist your login
                session on the website.
                <br />
              </li>
            </ol>
          </div>

          {/* Modifications */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Modifications</h3>
            <p>
              This Privacy Policy may be amended from time to time in order to
              maintain compliance with the law and to reflect any changes to our
              data collection process. When we amend this Privacy Policy we will
              update the "Effective Date" at the top of this Privacy Policy. We
              recommend that our users periodically review our Privacy Policy to
              ensure that they are notified of any updates. If necessary, we may
              notify users by email of changes to this Privacy Policy.
            </p>
          </div>

          {/* Contact Information */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Contact Information</h3>
            <p>
              If you have any questions, concerns or complaints, you can contact
              our privacy officer, Torrance Klimoski, at:
              <br />
              <br />
              tjklimoski@gmail.com
              <br />
              (305) 877-6434
              <br />
              172 Evergreen Rd., Hiawsse, GA, 30546
            </p>
          </div>
        </div>
      </Container>
    </main>
  );
}
