import Container from "@/components/util/Container";

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen">
      <Container>
        {/* TERMS OF SERVICE GENERATED BY LAWDEPOT */}
        <div className=" px-6 py-4 bg-base-100 opacity-80 backdrop-blur-md w-full mx-auto max-w-3xl">
          <h2 className="text-center font-bold underline mb-1">
            TERMS AND CONDITIONS
          </h2>
          <p>
            These terms and conditions (the "Terms and Conditions") govern the
            use of
            <span className="font-bold">watchparty-six.vercel.app</span>
            (the "Site"). This Site is owned and operated by Torrance Klimoski.
            This Site is a social network and event creator.
            <br />
            <br />
            By using this Site, you indicate that you have read and understand
            these Terms and Conditions and agree to abide by them at all times.
          </p>

          {/* Intellectual Property */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Intellectual Property</h3>
            <p>
              All content published and made available on our Site is the
              property of Torrance Klimoski and the Site's creators. This
              includes, but is not limited to images, text, logos, documents,
              downloadable files and anything that contributes to the
              composition of our Site.
            </p>
          </div>

          {/* Acceptable Use */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Acceptable Use</h3>
            <p>
              As a user of our Site, you agree to use our Site legally, not to
              use our Site for illegal purposes, and not to:
            </p>

            <ul className="list-disc [&>*]:mb-5 pl-8">
              <li>Harass or mistreat other users of our Site;</li>
              <li>Violate the rights of other users of our Site;</li>
              <li>
                Violate the intellectual property rights of the Site owners or
                any third party to the Site;
              </li>
              <li>Hack into the account of another user of the Site;</li>
              <li>Act in any way that could be considered fraudulent; or</li>
              <li>
                Post any material that may be deemed inappropriate or offensive.
              </li>
            </ul>
            <p>
              If we believe you are using our Site illegally or in a manner that
              violates these Terms and Conditions, we reserve the right to
              limit, suspend or terminate your access to our Site. We also
              reserve the right to take any legal steps necessary to prevent you
              from accessing our Site.
            </p>
          </div>

          {/* User Contributions */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">User Contributions</h3>
            <p>Users may post the following information on our Site:</p>
            <ul className="list-disc [&>*]:mb-5 pl-8">
              <li>Public comments; and</li>
              <li>
                Public WatchParty events that share location and time of the
                event.
              </li>
            </ul>
            <p>
              By posting publicly on our Site, you agree not to act illegally or
              violate these Terms and Conditions.
            </p>
          </div>

          {/* Accounts */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Accounts</h3>
            <p>
              When you create an account on our Site, you agree to the
              following:
            </p>
            <ol className="list-decimal [&>*]:mb-5 pl-8">
              <li>
                You are solely responsible for your account and the security and
                privacy of your account, including passwords or sensitive
                information attached to that account; and
              </li>
              <li>
                All personal information you provide to us through your account
                is up to date, accurate, and truthful and that you will update
                your personal information if it changes.
              </li>
              {/* I added in: */}
              <li>
                All user accounts, and any related data to that user account, is
                deleted after a period of 14 days from the date of creating the
                user account.
              </li>
            </ol>
            <p>
              We reserve the right to suspend or terminate your account if you
              are using our Site illegally or if you violate these Terms and
              Conditions.
            </p>
          </div>

          {/* User Goods and Services */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">
              User Goods and Services
            </h3>
            <p>
              Our Site allows users to sell goods and services. We do not assume
              any responsibility for the goods and services users sell on our
              Site. We cannot guarantee the quality or accuracy of any goods and
              services sold by users on our Site. However, if we are made aware
              that a user is violating these Terms and Conditions, we reserve
              the right to suspend or prohibit the user from selling goods and
              services on our Site.
            </p>
          </div>

          {/* Links to Other Websites */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">
              Links to Other Websites
            </h3>
            <p>
              Our Site contains links to third party websites or services that
              we do not own or control. We are not responsible for the content,
              policies, or practices of any third party website or service
              linked to on our Site. It is your responsibility to read the terms
              and conditions and privacy policies of these third party websites
              before using these sites.
            </p>
          </div>

          {/*  Limitation of Liability */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">
              Limitation of Liability
            </h3>
            <p>
              Torrance Klimoski and our directors, officers, agents, employees,
              subsidiaries, and affiliates will not be liable for any actions,
              claims, losses, damages, liabilities and expenses including legal
              fees from your use of the Site.
            </p>
          </div>

          {/*  Indemnity */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Indemnity</h3>
            <p>
              Except where prohibited by law, by using this Site you indemnify
              and hold harmless Torrance Klimoski and our directors, officers,
              agents, employees, subsidiaries, and affiliates from any actions,
              claims, losses, damages, liabilities and expenses including legal
              fees arising out of your use of our Site or your violation of
              these Terms and Conditions.
            </p>
          </div>

          {/* Applicable Law */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Applicable Law</h3>
            <p>
              These Terms and Conditions are governed by the laws of the State
              of Georgia.
            </p>
          </div>

          {/* Severability */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Severability</h3>
            <p>
              If at any time any of the provisions set forth in these Terms and
              Conditions are found to be inconsistent or invalid under
              applicable laws, those provisions will be deemed void and will be
              removed from these Terms and Conditions. All other provisions will
              not be affected by the removal and the rest of these Terms and
              Conditions will still be considered valid.
            </p>
          </div>

          {/* Changes */}
          <div className="mt-4">
            <h3 className="font-bold underline mb-1">Changes</h3>
            <p>
              These Terms and Conditions may be amended from time to time in
              order to maintain compliance with the law and to reflect any
              changes to the way we operate our Site and the way we expect users
              to behave on our Site. We will notify users by email of changes to
              these Terms and Conditions or post a notice on our Site.
            </p>
          </div>

          {/* Contact Details */}
          <div className="my-4">
            <h3 className="font-bold underline mb-1">Contact Details</h3>
            <p>
              Please contact us if you have any questions or concerns. Our
              contact details are as follows:
              <br />
              <br />
              (305) 877-6434
              <br />
              tjklimoski@gmail.com
              <br />
              172 Evergreen Rd., Hiawassee, GA, 30546
            </p>
          </div>

          <p>Effective Date: 5th day of November, 2023</p>
        </div>
      </Container>
    </main>
  );
}
